# basic options posso escrever qualquer coisa
title: JASON SITE
author: Jason Mejia GitHub User
email: jasonemjia@domain.com
description: A site for you to get to know me
twitter_username: jasonjekyllrb
github_username:  jasonjekyll

# Build settings
markdown: kramdown
theme: minima
